FROM python:3.11

RUN useradd -mU tradero && \
    mkdir -p /vol/tradero/media && \
    mkdir -p /vol/tradero/static && \
    mkdir -p /vol/tradero/log && \
    chown -R tradero:tradero /vol/tradero && \
    chmod -R 755 /vol/tradero && \
    python -m pip install pipenv

WORKDIR /home/tradero

USER root

COPY ./tradero tradero
COPY ./base base
COPY dockerfiles/tradero_uwsgi.ini .
COPY dockerfiles/django_tasks.sh .
COPY dockerfiles/supervisor.conf .
COPY dockerfiles/.env_file tradero/.env
COPY Pipfile Pipfile.lock pytest.ini pyproject.toml .coveragerc manage.py .
COPY dockerfiles/instance_entrypoint.sh .
RUN chown -R tradero:tradero /home/tradero
RUN chmod a+x /home/tradero/django_tasks.sh
RUN mkdir /run/daphne && chown -R tradero:tradero /run/daphne

ENV PYTHONUNBUFFERED=1
ENV PIPENV_VENV_IN_PROJECT=1
ENV PATH="/home/tradero:/home/tradero/.venv/bin:${PATH}"

USER tradero
RUN pipenv install
# Meantime fix
RUN pipenv run pip install -e git+https://github.com/math-a3k/django-ai.git@tradero#egg=django_ai

CMD ["/bin/bash", "./instance_entrypoint.sh"]
