FROM python:3.11

# RUN pacman -Syu python python-setuptools python-pipenv supervisor git postgresql-libs --noconfirm && yes | pacman -Scc

RUN useradd -mU tradero && \
    mkdir -p /vol/tradero/{media,static,db,log} && \
    chown -R tradero:tradero /vol/tradero && \
    chmod -R 755 /vol/tradero && \
    python -m pip install pipenv

WORKDIR /home/tradero

USER root

COPY ./tradero tradero
COPY ./base base
COPY dockerfiles/supervisor.conf .
COPY dockerfiles/.env_file tradero/.env
COPY Pipfile Pipfile.lock pytest.ini pyproject.toml .coveragerc manage.py .
RUN chown -R tradero:tradero /home/tradero

ENV PYTHONUNBUFFERED=1
ENV PIPENV_VENV_IN_PROJECT=1
ENV PATH="/home/tradero:/home/tradero/.venv/bin:${PATH}"

USER tradero
RUN pipenv install
# Meantime fix
RUN pipenv run pip install -e git+https://github.com/math-a3k/django-ai.git@tradero#egg=django_ai

CMD ["pipenv", "run", "celery", "-A", "tradero", "worker", "-l", "INFO", "-Q", "symbols,bots"]
