# Generated by Django 4.2.3 on 2023-08-01 04:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "base",
            "0003_traderobot_alter_trainingdata_options_symbol_info_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="tradehistory",
            name="timestamp_cancelled",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Timestamp - Cancelled"
            ),
        ),
        migrations.AlterField(
            model_name="traderobotlog",
            name="action",
            field=models.SmallIntegerField(
                choices=[
                    (-1, "Error"),
                    (0, "Hold"),
                    (1, "Buy"),
                    (2, "Sell"),
                    (3, "Jump"),
                    (4, "Turn ON"),
                    (5, "Turn OFF"),
                    (6, "Reset"),
                ],
                verbose_name="Bot Action",
            ),
        ),
    ]
