# Generated by Django 4.2.4 on 2023-08-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_tradehistory_timestamp_cancelled_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="kline",
            options={
                "ordering": ["-time_close"],
                "verbose_name": "Kline",
                "verbose_name_plural": "Klines",
            },
        ),
        migrations.AddConstraint(
            model_name="kline",
            constraint=models.UniqueConstraint(
                fields=("symbol", "time_close", "time_interval"),
                name="klines_unique_symbol_time",
            ),
        ),
    ]
