# Generated by Django 4.2.4 on 2023-08-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_alter_kline_options_kline_klines_unique_symbol_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradehistory",
            name="commission_buying",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=40,
                null=True,
                verbose_name="Comission (Buying)",
            ),
        ),
        migrations.AddField(
            model_name="tradehistory",
            name="commission_buying_asset",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Comission Asset (Buying)",
            ),
        ),
        migrations.AddField(
            model_name="tradehistory",
            name="commission_selling",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=40,
                null=True,
                verbose_name="Comission (Selling)",
            ),
        ),
        migrations.AddField(
            model_name="tradehistory",
            name="commission_selling_asset",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Comission Asset (Selling)",
            ),
        ),
    ]
