# Generated by Django 4.2.4 on 2023-08-05 09:11
from decimal import Decimal

from django.db import migrations

"""
As model methods should be unavailable to migrations as the code can change,
the relevant snapshots are included.
"""


def get_commission(receipt):
    """
    Snapshot of utils.get_commission
    """
    commission = sum(
        [Decimal(fill["commission"]) for fill in receipt["fills"]]
    )
    return commission, receipt["fills"][0]["commissionAsset"]


def fix_typo_in_dummy_receipt(receipt):
    if receipt["orderId"] == "DUMMY":
        if receipt["fills"][0].get("commsssionAsset", False):
            receipt["fills"][0]["commissionAsset"] = receipt["fills"][0][
                "commsssionAsset"
            ]
            del receipt["fills"][0]["commsssionAsset"]
    return receipt


def fix_objects(apps, schema_editor):
    TraderoBot = apps.get_model("base", "TraderoBot")
    TradeHistory = apps.get_model("base", "TradeHistory")

    for bot in TraderoBot.objects.all():
        if bot.receipt_buying:
            bot.receipt_buying = fix_typo_in_dummy_receipt(bot.receipt_buying)
        if bot.receipt_selling:
            bot.receipt_selling = fix_typo_in_dummy_receipt(
                bot.receipt_selling
            )
        bot.save()

    for th in TradeHistory.objects.all():
        if th.receipt_buying:
            th.receipt_buying = fix_typo_in_dummy_receipt(th.receipt_buying)
            (
                th.commission_buying,
                th.commission_buying_asset,
            ) = get_commission(th.receipt_buying)
        if th.receipt_selling:
            th.receipt_selling = fix_typo_in_dummy_receipt(th.receipt_selling)
            (
                th.commission_selling,
                th.commission_selling_asset,
            ) = get_commission(th.receipt_selling)
        th.save()


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0006_tradehistory_comission_buying_and_more"),
    ]

    operations = [
        migrations.RunPython(
            code=fix_objects, reverse_code=migrations.RunPython.noop
        )
    ]
