# Generated by Django 4.2.4 on 2023-08-09 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_groups_for_users(apps, schema_editor):
    User = apps.get_model("base", "User")
    TraderoBotGroup = apps.get_model("base", "TraderoBotGroup")
    for user in User.objects.all():
        group, _ = TraderoBotGroup.objects.get_or_create(user=user)


def assign_groups_to_bots(apps, schema_editor):
    TraderoBot = apps.get_model("base", "TraderoBot")
    TraderoBotGroup = apps.get_model("base", "TraderoBotGroup")
    for bot in TraderoBot.objects.all():
        group = TraderoBotGroup.objects.filter(user=bot.user).first()
        bot.group = group
        bot.save()


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0007_fix_typo_in_dummy_receipts"),
    ]

    operations = [
        migrations.CreateModel(
            name="TraderoBotGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "others",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Others"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="botgroups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tradero Bots Group",
                "verbose_name_plural": "Tradero Bots Groups",
            },
        ),
        migrations.RunPython(
            code=create_groups_for_users,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name="traderobot",
            name="group",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bots",
                to="base.traderobotgroup",
                verbose_name="Group",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(
            code=assign_groups_to_bots, reverse_code=migrations.RunPython.noop
        ),
    ]
