# Generated by Django 4.2.4 on 2023-08-12 18:50

from django.db import migrations, models


def set_variation_range_to_variation(apps, schema_editor):
    """
    Set initial value of variation_range to variation, this should
    provide the same prediction results as previously while new data arrives.

    To speed up the process, you may reset the symbols to have the klines
    and training data recreated with the extra information.
    """
    Kline = apps.get_model("base", "Kline")
    TrainingData = apps.get_model("base", "trainingdata")
    Kline.objects.all().update(variation_range=models.F("variation"))
    TrainingData.objects.all().update(
        variation_range_01=models.F("variation_01"),
        variation_range_02=models.F("variation_02"),
        variation_range_03=models.F("variation_03"),
        variation_range_04=models.F("variation_04"),
        variation_range_05=models.F("variation_05"),
        variation_range_06=models.F("variation_06"),
        variation_range_07=models.F("variation_07"),
        variation_range_08=models.F("variation_08"),
        variation_range_09=models.F("variation_09"),
        variation_range_10=models.F("variation_10"),
        variation_range_11=models.F("variation_11"),
        variation_range_12=models.F("variation_12"),
        variation_range_13=models.F("variation_13"),
        variation_range_14=models.F("variation_14"),
        variation_range_15=models.F("variation_15"),
        variation_range_16=models.F("variation_16"),
        variation_range_17=models.F("variation_17"),
        variation_range_18=models.F("variation_18"),
        variation_range_19=models.F("variation_19"),
        variation_range_20=models.F("variation_20"),
    )


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0008_traderobotgroup_traderobot_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="kline",
            name="variation_range",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=20,
                null=True,
                verbose_name="Variation Range",
            ),
        ),
        migrations.AddField(
            model_name="trainingdata",
            name="variation_range_01",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=20,
                null=True,
                verbose_name="Variation Range (t-1)",
            ),
        ),
        migrations.AddField(
            model_name="trainingdata",
            name="variation_range_02",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=20,
                null=True,
                verbose_name="Variation Range (t-2)",
            ),
        ),
        migrations.AddField(
            model_name="trainingdata",
            name="variation_range_03",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=20,
                null=True,
                verbose_name="Variation Range (t-3)",
            ),
        ),
        migrations.AddField(
            model_name="trainingdata",
            name="variation_range_04",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=20,
                null=True,
                verbose_name="Variation Range (t-4)",
            ),
        ),
        migrations.AddField(
            model_name="trainingdata",
            name="variation_range_05",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=20,
                null=True,
                verbose_name="Variation Range (t-5)",
            ),
        ),
        migrations.AddField(
            model_name="trainingdata",
            name="variation_range_06",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=20,
                null=True,
                verbose_name="Variation Range (t-6)",
            ),
        ),
        migrations.AddField(
            model_name="trainingdata",
            name="variation_range_07",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=20,
                null=True,
                verbose_name="Variation Range (t-7)",
            ),
        ),
        migrations.AddField(
            model_name="trainingdata",
            name="variation_range_08",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=20,
                null=True,
                verbose_name="Variation Range (t-8)",
            ),
        ),
        migrations.AddField(
            model_name="trainingdata",
            name="variation_range_09",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=20,
                null=True,
                verbose_name="Variation Range (t-9)",
            ),
        ),
        migrations.AddField(
            model_name="trainingdata",
            name="variation_range_10",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=20,
                null=True,
                verbose_name="Variation Range (t-10)",
            ),
        ),
        migrations.AddField(
            model_name="trainingdata",
            name="variation_range_11",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=20,
                null=True,
                verbose_name="Variation Range (t-11)",
            ),
        ),
        migrations.AddField(
            model_name="trainingdata",
            name="variation_range_12",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=20,
                null=True,
                verbose_name="Variation Range (t-12)",
            ),
        ),
        migrations.AddField(
            model_name="trainingdata",
            name="variation_range_13",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=20,
                null=True,
                verbose_name="Variation Range (t-13)",
            ),
        ),
        migrations.AddField(
            model_name="trainingdata",
            name="variation_range_14",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=20,
                null=True,
                verbose_name="Variation Range (t-14)",
            ),
        ),
        migrations.AddField(
            model_name="trainingdata",
            name="variation_range_15",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=20,
                null=True,
                verbose_name="Variation Range (t-15)",
            ),
        ),
        migrations.AddField(
            model_name="trainingdata",
            name="variation_range_16",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=20,
                null=True,
                verbose_name="Variation Range (t-16)",
            ),
        ),
        migrations.AddField(
            model_name="trainingdata",
            name="variation_range_17",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=20,
                null=True,
                verbose_name="Variation Range (t-17)",
            ),
        ),
        migrations.AddField(
            model_name="trainingdata",
            name="variation_range_18",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=20,
                null=True,
                verbose_name="Variation Range (t-18)",
            ),
        ),
        migrations.AddField(
            model_name="trainingdata",
            name="variation_range_19",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=20,
                null=True,
                verbose_name="Variation Range (t-19)",
            ),
        ),
        migrations.AddField(
            model_name="trainingdata",
            name="variation_range_20",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=20,
                null=True,
                verbose_name="Variation Range (t-20)",
            ),
        ),
        migrations.RunPython(
            code=set_variation_range_to_variation,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="kline",
            name="variation_range",
            field=models.DecimalField(
                decimal_places=8,
                default=0,
                max_digits=20,
                verbose_name="Variation Range",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="trainingdata",
            name="variation_range_01",
            field=models.DecimalField(
                decimal_places=8,
                default=0,
                max_digits=20,
                verbose_name="Variation Range (t-1)",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="trainingdata",
            name="variation_range_02",
            field=models.DecimalField(
                decimal_places=8,
                default=0,
                max_digits=20,
                verbose_name="Variation Range (t-2)",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="trainingdata",
            name="variation_range_03",
            field=models.DecimalField(
                decimal_places=8,
                default=0,
                max_digits=20,
                verbose_name="Variation Range (t-3)",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="trainingdata",
            name="variation_range_04",
            field=models.DecimalField(
                decimal_places=8,
                default=0,
                max_digits=20,
                verbose_name="Variation Range (t-4)",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="trainingdata",
            name="variation_range_05",
            field=models.DecimalField(
                decimal_places=8,
                default=0,
                max_digits=20,
                verbose_name="Variation Range (t-5)",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="trainingdata",
            name="variation_range_06",
            field=models.DecimalField(
                decimal_places=8,
                default=0,
                max_digits=20,
                verbose_name="Variation Range (t-6)",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="trainingdata",
            name="variation_range_07",
            field=models.DecimalField(
                decimal_places=8,
                default=0,
                max_digits=20,
                verbose_name="Variation Range (t-7)",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="trainingdata",
            name="variation_range_08",
            field=models.DecimalField(
                decimal_places=8,
                default=0,
                max_digits=20,
                verbose_name="Variation Range (t-8)",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="trainingdata",
            name="variation_range_09",
            field=models.DecimalField(
                decimal_places=8,
                default=0,
                max_digits=20,
                verbose_name="Variation Range (t-9)",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="trainingdata",
            name="variation_range_10",
            field=models.DecimalField(
                decimal_places=8,
                default=0,
                max_digits=20,
                verbose_name="Variation Range (t-10)",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="trainingdata",
            name="variation_range_11",
            field=models.DecimalField(
                decimal_places=8,
                default=0,
                max_digits=20,
                verbose_name="Variation Range (t-11)",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="trainingdata",
            name="variation_range_12",
            field=models.DecimalField(
                decimal_places=8,
                default=0,
                max_digits=20,
                verbose_name="Variation Range (t-12)",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="trainingdata",
            name="variation_range_13",
            field=models.DecimalField(
                decimal_places=8,
                default=0,
                max_digits=20,
                verbose_name="Variation Range (t-13)",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="trainingdata",
            name="variation_range_14",
            field=models.DecimalField(
                decimal_places=8,
                default=0,
                max_digits=20,
                verbose_name="Variation Range (t-14)",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="trainingdata",
            name="variation_range_15",
            field=models.DecimalField(
                decimal_places=8,
                default=0,
                max_digits=20,
                verbose_name="Variation Range (t-15)",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="trainingdata",
            name="variation_range_16",
            field=models.DecimalField(
                decimal_places=8,
                default=0,
                max_digits=20,
                verbose_name="Variation Range (t-16)",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="trainingdata",
            name="variation_range_17",
            field=models.DecimalField(
                decimal_places=8,
                default=0,
                max_digits=20,
                verbose_name="Variation Range (t-17)",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="trainingdata",
            name="variation_range_18",
            field=models.DecimalField(
                decimal_places=8,
                default=0,
                max_digits=20,
                verbose_name="Variation Range (t-18)",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="trainingdata",
            name="variation_range_19",
            field=models.DecimalField(
                decimal_places=8,
                default=0,
                max_digits=20,
                verbose_name="Variation Range (t-19)",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="trainingdata",
            name="variation_range_20",
            field=models.DecimalField(
                decimal_places=8,
                default=0,
                max_digits=20,
                verbose_name="Variation Range (t-20)",
            ),
            preserve_default=False,
        ),
    ]
