# Generated by Django 4.2.4 on 2023-08-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0009_kline_variation_range_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="traderobot",
            name="jumpy_whitelist",
            field=models.CharField(
                blank=True,
                max_length=1024,
                null=True,
                verbose_name="Jumpy Symbols' Whitelist",
            ),
        ),
        migrations.AlterField(
            model_name="traderobot",
            name="jumpy_blacklist",
            field=models.CharField(
                blank=True,
                max_length=1024,
                null=True,
                verbose_name="Jumpy Symbols' Blacklist",
            ),
        ),
    ]
