# Generated by Django 4.2.4 on 2023-08-17 12:12

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0010_traderobot_jumpy_whitelist_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="traderobot",
            name="fund_quote_asset",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=40,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("15"))
                ],
                verbose_name="Fund (Quote Asset)",
            ),
        ),
        migrations.AlterField(
            model_name="traderobot",
            name="fund_quote_asset_initial",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=40,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("15"))
                ],
                verbose_name="Initial Fund (Quote Asset)",
            ),
        ),
    ]
