# Generated by Django 4.2.4 on 2023-08-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0011_alter_traderobot_fund_quote_asset_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="traderobot",
            name="strategy_params",
            field=models.CharField(
                blank=True,
                max_length=510,
                null=True,
                verbose_name="Strategy parameters",
            ),
        ),
    ]
