# Generated by Django 4.2.4 on 2023-08-22 03:51

from django.db import migrations, models


def refresh_th_fields(apps, schema_editor):
    TradeHistory = apps.get_model("base", "TradeHistory")
    for th in TradeHistory.objects.all():
        th.save()


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0012_alter_traderobot_strategy_params"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tradehistory",
            old_name="fund_quote_asset",
            new_name="fund_quote_asset_exec",
        ),
        migrations.AddField(
            model_name="tradehistory",
            name="fund_quote_asset_return",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=40,
                null=True,
                verbose_name="Fund (Quote Asset) Returned",
            ),
        ),
        migrations.AlterField(
            model_name="tradehistory",
            name="fund_quote_asset_exec",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=40,
                null=True,
                verbose_name="Fund (Quote Asset) Executed",
            ),
        ),
        migrations.AddIndex(
            model_name="tradehistory",
            index=models.Index(
                fields=["-timestamp_selling"],
                name="base_tradeh_timesta_8e8299_idx",
            ),
        ),
        migrations.RunPython(
            code=refresh_th_fields,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
