# Generated by Django 4.2.4 on 2023-08-22 05:49

from django.db import migrations, models
from django.utils import timezone


def populate_variation_range(apps, schema_editor):
    """
    Set initial value of variation_range.
    """
    Kline = apps.get_model("base", "Kline")
    Symbol = apps.get_model("base", "Symbol")
    Kline.objects.all().update(variation_range=models.F("variation"))
    symbols = Symbol.objects.filter(
        status="TRADING",
        is_enabled=True,
    )
    for symbol in symbols:
        klines_24h = symbol.klines.order_by("time_close").filter(
            time_close__gte=timezone.now() - timezone.timedelta(days=1)
        )
        ceil_floor = klines_24h.aggregate(
            models.Min("price_low", default=1),
            models.Max("price_high", default=1),
        )
        symbol.variation_range_24h = (
            ceil_floor["price_high__max"] / ceil_floor["price_low__min"] * 100
        ) - 100
        symbol.save()


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0013_rename_tradehistory_fund_quote_asset_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="symbol",
            name="variation_range_24h",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=16,
                null=True,
                verbose_name="Variation Range - 24 hs",
            ),
        ),
        migrations.RunPython(
            code=populate_variation_range,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
