# Generated by Django 4.2.4 on 2023-08-23 12:00

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0014_symbol_variation_range_24h"),
    ]

    operations = [
        migrations.AlterField(
            model_name="traderobot",
            name="fund_quote_asset_initial",
            field=models.DecimalField(
                decimal_places=8,
                default=20,
                max_digits=40,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("15"))
                ],
                verbose_name="Initial Fund (Quote Asset)",
            ),
            preserve_default=False,
        ),
    ]
