# Generated by Django 4.2.4 on 2023-09-02 00:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0017_rename_variation_tradehistory_variation_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kline",
            name="number_of_trades",
            field=models.DecimalField(
                decimal_places=8,
                max_digits=40,
                verbose_name="Number of Trades",
            ),
        ),
        migrations.AlterField(
            model_name="kline",
            name="price_close",
            field=models.DecimalField(
                decimal_places=8, max_digits=40, verbose_name="Price Close"
            ),
        ),
        migrations.AlterField(
            model_name="kline",
            name="price_high",
            field=models.DecimalField(
                decimal_places=8, max_digits=40, verbose_name="Price High"
            ),
        ),
        migrations.AlterField(
            model_name="kline",
            name="price_low",
            field=models.DecimalField(
                decimal_places=8, max_digits=40, verbose_name="Price Low"
            ),
        ),
        migrations.AlterField(
            model_name="kline",
            name="price_open",
            field=models.DecimalField(
                decimal_places=8, max_digits=40, verbose_name="Price Open"
            ),
        ),
        migrations.AlterField(
            model_name="kline",
            name="variation",
            field=models.DecimalField(
                decimal_places=8, max_digits=40, verbose_name="Variation"
            ),
        ),
        migrations.AlterField(
            model_name="kline",
            name="variation_range",
            field=models.DecimalField(
                decimal_places=8, max_digits=40, verbose_name="Variation Range"
            ),
        ),
        migrations.AlterField(
            model_name="kline",
            name="volume",
            field=models.DecimalField(
                decimal_places=8, max_digits=40, verbose_name="Volume"
            ),
        ),
        migrations.AlterField(
            model_name="kline",
            name="volume_quote_asset",
            field=models.DecimalField(
                decimal_places=8,
                max_digits=40,
                verbose_name="Quote Asset Volume",
            ),
        ),
        migrations.AlterField(
            model_name="kline",
            name="volume_tb_base_asset",
            field=models.DecimalField(
                decimal_places=8,
                max_digits=40,
                verbose_name="Taker buy base asset volume",
            ),
        ),
        migrations.AlterField(
            model_name="kline",
            name="volume_tb_quote_asset",
            field=models.DecimalField(
                decimal_places=8,
                max_digits=40,
                verbose_name="Taker buy quote asset volume Price",
            ),
        ),
        migrations.AlterField(
            model_name="symbol",
            name="volume_quote_asset",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=40,
                null=True,
                verbose_name="Quote Asset Volume (24h)",
            ),
        ),
        migrations.AlterField(
            model_name="trainingdata",
            name="variation",
            field=models.DecimalField(
                decimal_places=8, max_digits=40, verbose_name="Variation (t)"
            ),
        ),
        migrations.AlterField(
            model_name="trainingdata",
            name="variation_01",
            field=models.DecimalField(
                decimal_places=8, max_digits=40, verbose_name="Variation (t-1)"
            ),
        ),
        migrations.AlterField(
            model_name="trainingdata",
            name="variation_02",
            field=models.DecimalField(
                decimal_places=8, max_digits=40, verbose_name="Variation (t-2)"
            ),
        ),
        migrations.AlterField(
            model_name="trainingdata",
            name="variation_03",
            field=models.DecimalField(
                decimal_places=8, max_digits=40, verbose_name="Variation (t-3)"
            ),
        ),
        migrations.AlterField(
            model_name="trainingdata",
            name="variation_04",
            field=models.DecimalField(
                decimal_places=8, max_digits=40, verbose_name="Variation (t-4)"
            ),
        ),
        migrations.AlterField(
            model_name="trainingdata",
            name="variation_05",
            field=models.DecimalField(
                decimal_places=8, max_digits=40, verbose_name="Variation (t-5)"
            ),
        ),
        migrations.AlterField(
            model_name="trainingdata",
            name="variation_06",
            field=models.DecimalField(
                decimal_places=8, max_digits=40, verbose_name="Variation (t-6)"
            ),
        ),
        migrations.AlterField(
            model_name="trainingdata",
            name="variation_07",
            field=models.DecimalField(
                decimal_places=8, max_digits=40, verbose_name="Variation (t-7)"
            ),
        ),
        migrations.AlterField(
            model_name="trainingdata",
            name="variation_08",
            field=models.DecimalField(
                decimal_places=8, max_digits=40, verbose_name="Variation (t-8)"
            ),
        ),
        migrations.AlterField(
            model_name="trainingdata",
            name="variation_09",
            field=models.DecimalField(
                decimal_places=8, max_digits=40, verbose_name="Variation (t-9)"
            ),
        ),
        migrations.AlterField(
            model_name="trainingdata",
            name="variation_10",
            field=models.DecimalField(
                decimal_places=8,
                max_digits=40,
                verbose_name="Variation (t-10)",
            ),
        ),
        migrations.AlterField(
            model_name="trainingdata",
            name="variation_11",
            field=models.DecimalField(
                decimal_places=8,
                max_digits=40,
                verbose_name="Variation (t-11)",
            ),
        ),
        migrations.AlterField(
            model_name="trainingdata",
            name="variation_12",
            field=models.DecimalField(
                decimal_places=8,
                max_digits=40,
                verbose_name="Variation (t-12)",
            ),
        ),
        migrations.AlterField(
            model_name="trainingdata",
            name="variation_13",
            field=models.DecimalField(
                decimal_places=8,
                max_digits=40,
                verbose_name="Variation (t-13)",
            ),
        ),
        migrations.AlterField(
            model_name="trainingdata",
            name="variation_14",
            field=models.DecimalField(
                decimal_places=8,
                max_digits=40,
                verbose_name="Variation (t-14)",
            ),
        ),
        migrations.AlterField(
            model_name="trainingdata",
            name="variation_15",
            field=models.DecimalField(
                decimal_places=8,
                max_digits=40,
                verbose_name="Variation (t-15)",
            ),
        ),
        migrations.AlterField(
            model_name="trainingdata",
            name="variation_16",
            field=models.DecimalField(
                decimal_places=8,
                max_digits=40,
                verbose_name="Variation (t-16)",
            ),
        ),
        migrations.AlterField(
            model_name="trainingdata",
            name="variation_17",
            field=models.DecimalField(
                decimal_places=8,
                max_digits=40,
                verbose_name="Variation (t-17)",
            ),
        ),
        migrations.AlterField(
            model_name="trainingdata",
            name="variation_18",
            field=models.DecimalField(
                decimal_places=8,
                max_digits=40,
                verbose_name="Variation (t-18)",
            ),
        ),
        migrations.AlterField(
            model_name="trainingdata",
            name="variation_19",
            field=models.DecimalField(
                decimal_places=8,
                max_digits=40,
                verbose_name="Variation (t-19)",
            ),
        ),
        migrations.AlterField(
            model_name="trainingdata",
            name="variation_20",
            field=models.DecimalField(
                decimal_places=8,
                max_digits=40,
                verbose_name="Variation (t-20)",
            ),
        ),
        migrations.AlterField(
            model_name="trainingdata",
            name="variation_range_01",
            field=models.DecimalField(
                decimal_places=8,
                max_digits=40,
                verbose_name="Variation Range (t-1)",
            ),
        ),
        migrations.AlterField(
            model_name="trainingdata",
            name="variation_range_02",
            field=models.DecimalField(
                decimal_places=8,
                max_digits=40,
                verbose_name="Variation Range (t-2)",
            ),
        ),
        migrations.AlterField(
            model_name="trainingdata",
            name="variation_range_03",
            field=models.DecimalField(
                decimal_places=8,
                max_digits=40,
                verbose_name="Variation Range (t-3)",
            ),
        ),
        migrations.AlterField(
            model_name="trainingdata",
            name="variation_range_04",
            field=models.DecimalField(
                decimal_places=8,
                max_digits=40,
                verbose_name="Variation Range (t-4)",
            ),
        ),
        migrations.AlterField(
            model_name="trainingdata",
            name="variation_range_05",
            field=models.DecimalField(
                decimal_places=8,
                max_digits=40,
                verbose_name="Variation Range (t-5)",
            ),
        ),
        migrations.AlterField(
            model_name="trainingdata",
            name="variation_range_06",
            field=models.DecimalField(
                decimal_places=8,
                max_digits=40,
                verbose_name="Variation Range (t-6)",
            ),
        ),
        migrations.AlterField(
            model_name="trainingdata",
            name="variation_range_07",
            field=models.DecimalField(
                decimal_places=8,
                max_digits=40,
                verbose_name="Variation Range (t-7)",
            ),
        ),
        migrations.AlterField(
            model_name="trainingdata",
            name="variation_range_08",
            field=models.DecimalField(
                decimal_places=8,
                max_digits=40,
                verbose_name="Variation Range (t-8)",
            ),
        ),
        migrations.AlterField(
            model_name="trainingdata",
            name="variation_range_09",
            field=models.DecimalField(
                decimal_places=8,
                max_digits=40,
                verbose_name="Variation Range (t-9)",
            ),
        ),
        migrations.AlterField(
            model_name="trainingdata",
            name="variation_range_10",
            field=models.DecimalField(
                decimal_places=8,
                max_digits=40,
                verbose_name="Variation Range (t-10)",
            ),
        ),
        migrations.AlterField(
            model_name="trainingdata",
            name="variation_range_11",
            field=models.DecimalField(
                decimal_places=8,
                max_digits=40,
                verbose_name="Variation Range (t-11)",
            ),
        ),
        migrations.AlterField(
            model_name="trainingdata",
            name="variation_range_12",
            field=models.DecimalField(
                decimal_places=8,
                max_digits=40,
                verbose_name="Variation Range (t-12)",
            ),
        ),
        migrations.AlterField(
            model_name="trainingdata",
            name="variation_range_13",
            field=models.DecimalField(
                decimal_places=8,
                max_digits=40,
                verbose_name="Variation Range (t-13)",
            ),
        ),
        migrations.AlterField(
            model_name="trainingdata",
            name="variation_range_14",
            field=models.DecimalField(
                decimal_places=8,
                max_digits=40,
                verbose_name="Variation Range (t-14)",
            ),
        ),
        migrations.AlterField(
            model_name="trainingdata",
            name="variation_range_15",
            field=models.DecimalField(
                decimal_places=8,
                max_digits=40,
                verbose_name="Variation Range (t-15)",
            ),
        ),
        migrations.AlterField(
            model_name="trainingdata",
            name="variation_range_16",
            field=models.DecimalField(
                decimal_places=8,
                max_digits=40,
                verbose_name="Variation Range (t-16)",
            ),
        ),
        migrations.AlterField(
            model_name="trainingdata",
            name="variation_range_17",
            field=models.DecimalField(
                decimal_places=8,
                max_digits=40,
                verbose_name="Variation Range (t-17)",
            ),
        ),
        migrations.AlterField(
            model_name="trainingdata",
            name="variation_range_18",
            field=models.DecimalField(
                decimal_places=8,
                max_digits=40,
                verbose_name="Variation Range (t-18)",
            ),
        ),
        migrations.AlterField(
            model_name="trainingdata",
            name="variation_range_19",
            field=models.DecimalField(
                decimal_places=8,
                max_digits=40,
                verbose_name="Variation Range (t-19)",
            ),
        ),
        migrations.AlterField(
            model_name="trainingdata",
            name="variation_range_20",
            field=models.DecimalField(
                decimal_places=8,
                max_digits=40,
                verbose_name="Variation Range (t-20)",
            ),
        ),
    ]
