# Generated by Django 4.2.5 on 2023-09-12 02:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0019_update_dummy_receipts"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bot_quota",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Maximum Bots for the User (0 for No Quota)",
                verbose_name="Bots' Quota",
            ),
        ),
    ]
