# Generated by Django 5.0.2 on 2024-07-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0020_user_bot_quota"),
    ]

    operations = [
        migrations.AddField(
            model_name="traderobotgroup",
            name="checkpoint",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Checkpoint - User"
            ),
        ),
        migrations.AlterField(
            model_name="traderobot",
            name="strategy_params",
            field=models.CharField(
                blank=True,
                help_text="(<a href='https://tradero.readthedocs.io/en/latest/trading_bots.html' target='_blank'>Strategy docs</a>)",
                max_length=510,
                null=True,
                verbose_name="Strategy parameters",
            ),
        ),
    ]
