# Generated by Django 5.0.2 on 2024-07-11 17:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0021_traderobotgroup_checkpoint_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="traderobotgroup",
            name="checkpoint",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                null=True,
                verbose_name="Checkpoint - User",
            ),
        ),
    ]
